#!/usr/bin/env bash
# deploy.sh — One-command ToolsDNS installer for Ubuntu/Debian VPS
#
# Installs ToolsDNS directly on the host with Redis caching,
# security hardening, and systemd services. Runs locally only.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/syedfahimdev/ToolsDNS/master/deploy.sh | bash
#   ./deploy.sh

set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
DIM='\033[2m'
NC='\033[0m'

info()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*"; exit 1; }
section() { echo -e "\n${BOLD}${CYAN}──── $* ────${NC}"; }
detail()  { echo -e "  ${DIM}$*${NC}"; }

# ── Config ────────────────────────────────────────────────────────────────────
INSTALL_DIR="${TOOLDNS_INSTALL_DIR:-/root/ToolsDNS}"
DATA_DIR="${TOOLDNS_DATA_DIR:-/root/.tooldns}"
PORT="${TOOLDNS_PORT:-8787}"
MCP_PORT="${TOOLDNS_MCP_PORT:-8788}"
SERVICE_USER="root"

# Files created — tracked for the summary
CREATED_FILES=()
CREATED_SERVICES=()

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║            ToolsDNS                    ║${NC}"
echo -e "${CYAN}║     VPS Installer (local)              ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════╝${NC}"
echo ""
echo "  Install dir : $INSTALL_DIR"
echo "  Data dir    : $DATA_DIR"
echo "  Port        : $PORT  (API — localhost only)"
echo "  MCP port    : $MCP_PORT  (MCP persistent HTTP)"
echo ""

# ── Root check ────────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || error "Run as root: sudo bash deploy.sh"

# ── System dependencies ───────────────────────────────────────────────────────
section "System dependencies"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq python3 python3-pip python3-venv git curl openssl redis-server
info "System packages installed (python3, pip, venv, git, curl, openssl, redis)"

# ── Redis ─────────────────────────────────────────────────────────────────────
section "Redis (L2 cache)"
systemctl enable redis-server
systemctl start redis-server
if redis-cli ping &>/dev/null; then
  info "Redis running — $(redis-server --version | head -1)"
else
  warn "Redis failed to start — ToolsDNS will use memory-only cache"
fi

# ── Clone / update repo ───────────────────────────────────────────────────────
section "ToolsDNS code"
if [[ -d "$INSTALL_DIR/.git" ]]; then
  info "Repo exists — pulling latest"
  git -C "$INSTALL_DIR" pull --ff-only
else
  info "Cloning repo to $INSTALL_DIR"
  git clone https://github.com/syedfahimdev/ToolsDNS.git "$INSTALL_DIR"
fi

# Make tooldns.sh executable and symlink to /usr/local/bin
chmod +x "$INSTALL_DIR/tooldns.sh"
ln -sf "$INSTALL_DIR/tooldns.sh" /usr/local/bin/tooldns
info "tooldns command available at /usr/local/bin/tooldns"

# ── Python environment ────────────────────────────────────────────────────────
section "Python environment"
python3 -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/pip" install -q --upgrade pip
"$INSTALL_DIR/.venv/bin/pip" install -q -e "$INSTALL_DIR"
"$INSTALL_DIR/.venv/bin/pip" install -q redis
info "Python virtualenv ready at $INSTALL_DIR/.venv (includes redis-py)"

# ── Data directory & config ───────────────────────────────────────────────────
section "Data directory & config"
mkdir -p "$DATA_DIR/skills" "$DATA_DIR/tools"
info "Directories: $DATA_DIR/skills  $DATA_DIR/tools"

CONFIG_FILE="$DATA_DIR/config.json"
if [[ ! -f "$CONFIG_FILE" ]]; then
  # Read Composio env vars if set, otherwise use placeholders
  _COMPOSIO_KEY="${COMPOSIO_API_KEY:-}"
  _COMPOSIO_URL="${COMPOSIO_MCP_URL:-}"
  _BROWSERUSE_KEY="${BROWSER_USE_API_KEY:-}"

  cat > "$CONFIG_FILE" << EOF
{
  "mcpServers": {
    "composio": {
      "url": "${_COMPOSIO_URL}",
      "headers": {}
    },
    "browseruse": {
      "command": "npx",
      "args": ["-y", "@anthropic/browseruse-mcp@latest"],
      "env": {
        "BROWSER_USE_API_KEY": "${_BROWSERUSE_KEY}"
      }
    }
  },
  "skillPaths": [
    "$DATA_DIR/skills"
  ]
}
EOF
  CREATED_FILES+=("$CONFIG_FILE")
  info "Created $CONFIG_FILE (includes Composio + Browser Use MCP)"
  [[ -z "$_COMPOSIO_URL" ]] && warn "Set COMPOSIO_MCP_URL in .env to enable Composio"
  [[ -z "$_BROWSERUSE_KEY" ]] && warn "Set BROWSER_USE_API_KEY in .env to enable Browser Use"
else
  info "Existing $CONFIG_FILE kept (not overwritten)"
fi

ENV_FILE="$DATA_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  API_KEY="td_$(openssl rand -hex 24)"
  cat > "$ENV_FILE" << EOF
# ToolsDNS configuration — generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Edit this file to customize your ToolsDNS instance.
# Restart the service after changes: systemctl restart tooldns tooldns-mcp

# ── API Server ────────────────────────────────────────────────
TOOLDNS_API_KEY=$API_KEY
TOOLDNS_HOST=127.0.0.1
TOOLDNS_PORT=$PORT
TOOLDNS_APP_NAME=ToolsDNS
TOOLDNS_APP_TAGLINE=DNS for AI Tools
TOOLDNS_REFRESH_INTERVAL=60

# ── MCP HTTP server ───────────────────────────────────────────
# Persistent connection — eliminates cold-start latency for agents
TOOLDNS_MCP_TRANSPORT=http
TOOLDNS_MCP_HOST=127.0.0.1
TOOLDNS_MCP_PORT=$MCP_PORT

# ── Redis (L2 cache) ─────────────────────────────────────────
TOOLDNS_REDIS_URL=redis://127.0.0.1:6379

# ── Composio (2,000+ managed tools) ──────────────────────────
# COMPOSIO_API_KEY=your_key_here
# COMPOSIO_MCP_URL=your_mcp_url_here

# ── Browser Use (web browsing for agents) ────────────────────
# BROWSER_USE_API_KEY=your_key_here
EOF
  CREATED_FILES+=("$ENV_FILE")
  info "Created $ENV_FILE"
else
  info "Existing $ENV_FILE kept (not overwritten)"
  API_KEY=$(grep "^TOOLDNS_API_KEY=" "$ENV_FILE" | cut -d= -f2- | tr -d ' ' || true)
  [[ -z "$API_KEY" ]] && API_KEY="(see $ENV_FILE)"

  # Add MCP vars to existing .env if missing
  if ! grep -q "^TOOLDNS_MCP_TRANSPORT=" "$ENV_FILE"; then
    cat >> "$ENV_FILE" << EOF

# ── MCP HTTP server (added by deploy.sh) ─────────────────────
TOOLDNS_MCP_TRANSPORT=http
TOOLDNS_MCP_HOST=127.0.0.1
TOOLDNS_MCP_PORT=$MCP_PORT
EOF
    info "Added MCP server config to $ENV_FILE"
  else
    MCP_PORT=$(grep "^TOOLDNS_MCP_PORT=" "$ENV_FILE" | cut -d= -f2- | tr -d ' ' || echo "$MCP_PORT")
  fi
fi

# ── Security hardening ────────────────────────────────────────────────────────
section "Security hardening"
chmod 700 "$DATA_DIR"
chmod 600 "$ENV_FILE"
info "Data dir (700) and .env (600) — owner-only access"

# ── Systemd services ──────────────────────────────────────────────────────────
section "Systemd services"

cat > /etc/systemd/system/tooldns.service << EOF
[Unit]
Description=ToolsDNS — AI Tool Discovery Service
Documentation=https://github.com/syedfahimdev/ToolsDNS
After=network.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$DATA_DIR/.env
ExecStart=$INSTALL_DIR/.venv/bin/python3 -m tooldns.cli serve
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=tooldns
ReadWritePaths=$DATA_DIR $INSTALL_DIR
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
CREATED_FILES+=("/etc/systemd/system/tooldns.service")

cat > /etc/systemd/system/tooldns-mcp.service << EOF
[Unit]
Description=ToolsDNS MCP Server (HTTP persistent)
Documentation=https://github.com/syedfahimdev/ToolsDNS
After=network.target tooldns.service
Wants=tooldns.service
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$DATA_DIR/.env
ExecStart=$INSTALL_DIR/.venv/bin/python3 -m tooldns.mcp_server
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=tooldns-mcp
ReadWritePaths=$DATA_DIR $INSTALL_DIR
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
CREATED_FILES+=("/etc/systemd/system/tooldns-mcp.service")
CREATED_SERVICES+=("tooldns" "tooldns-mcp")

systemctl daemon-reload
systemctl enable tooldns tooldns-mcp
systemctl restart tooldns
# Give the main API a moment before the MCP server connects
sleep 3
systemctl restart tooldns-mcp
info "Services enabled and started"

# ── Wait for API backend ──────────────────────────────────────────────────────
section "Waiting for services"
TOOLS_INDEXED="?"
for i in {1..18}; do
  HEALTH=$(curl -s --max-time 3 "http://localhost:$PORT/health" 2>/dev/null || true)
  if echo "$HEALTH" | grep -q '"healthy"'; then
    TOOLS_INDEXED=$(echo "$HEALTH" | python3 -c "import sys,json; print(json.load(sys.stdin).get('tools_indexed',0))" 2>/dev/null || echo "?")
    info "API healthy — $TOOLS_INDEXED tools indexed"
    break
  fi
  if [[ $i -eq 18 ]]; then
    warn "API slow to start — check: journalctl -u tooldns -n 30"
    break
  fi
  printf "  Waiting for API... (%ds)\r" "$((i * 5))"
  sleep 5
done

# Check MCP HTTP server — POST to /mcp/ is the correct method
MCP_OK=false
for i in {1..8}; do
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 3 \
    -X POST "http://127.0.0.1:${MCP_PORT}/mcp/" \
    -H "Accept: application/json, text/event-stream" \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"healthcheck","version":"1"}},"id":1}' \
    2>/dev/null || true)
  if [[ "$HTTP_CODE" == "200" ]]; then
    info "MCP server healthy — http://127.0.0.1:${MCP_PORT}/mcp/"
    MCP_OK=true
    break
  fi
  if [[ $i -eq 8 ]]; then
    warn "MCP server slow to start — check: journalctl -u tooldns-mcp -n 30"
    break
  fi
  printf "  Waiting for MCP... (%ds)\r" "$((i * 3))"
  sleep 3
done

# ── Final summary ─────────────────────────────────────────────────────────────

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                  ✅  ToolsDNS is installed!                     ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Services ─────────────────────────────────────────────────────────────────
echo -e "${BOLD}SERVICES${NC}"
echo -e "  API backend    → http://127.0.0.1:${PORT}          (systemd: tooldns)"
echo -e "  MCP server     → http://127.0.0.1:${MCP_PORT}/mcp/  (systemd: tooldns-mcp)"
echo -e "  Redis cache    → redis://127.0.0.1:6379            (systemd: redis-server)"
echo ""

# ── Files created ─────────────────────────────────────────────────────────────
echo -e "${BOLD}FILES CREATED${NC}"
echo -e "  Config (.env)  → ${ENV_FILE}  ${DIM}(chmod 600)${NC}"
echo -e "  Data dir       → ${DATA_DIR}  ${DIM}(chmod 700)${NC}"
echo -e "  Systemd        → /etc/systemd/system/tooldns.service"
echo -e "  Systemd        → /etc/systemd/system/tooldns-mcp.service"
echo -e "  App code       → ${INSTALL_DIR}"
echo -e "  CLI command    → /usr/local/bin/tooldns"
echo ""

# ── Credentials ──────────────────────────────────────────────────────────────
echo -e "${BOLD}YOUR API KEY${NC}"
echo -e "  ${YELLOW}${API_KEY}${NC}"
echo -e "  ${DIM}(stored in ${ENV_FILE})${NC}"
echo ""

# ── Where to edit ─────────────────────────────────────────────────────────────
echo -e "${BOLD}WHERE TO EDIT${NC}"
echo -e "  Server config   → ${ENV_FILE}"
echo -e "  Add tools       → ${DATA_DIR}/skills/  (drop skill folders here)"
echo -e "  Restart service → systemctl restart tooldns tooldns-mcp"
echo ""

# ── Connect an agent ─────────────────────────────────────────────────────────
echo -e "${BOLD}CONNECT AN AGENT — add this to your MCP config${NC}"
echo ""
cat << EOF
  {
    "mcpServers": {
      "tooldns": {
        "url": "http://127.0.0.1:${MCP_PORT}/mcp/",
        "headers": { "Authorization": "Bearer ${API_KEY}" }
      }
    }
  }
EOF
echo ""

# ── System prompt ─────────────────────────────────────────────────────────────
echo -e "${BOLD}SYSTEM PROMPT FOR YOUR AGENT${NC}"
echo -e "  ${YELLOW}http://127.0.0.1:${PORT}/v1/system-prompt${NC}"
echo -e "  ${DIM}(returns live tool count + usage instructions every session)${NC}"
echo ""

# ── Next steps ────────────────────────────────────────────────────────────────
echo -e "${BOLD}NEXT STEPS${NC}"
echo ""
echo -e "  1. ${BOLD}Add your first tools:${NC}"
echo -e "       tooldns add             # interactive — MCP server, skill, OpenAPI, etc."
echo -e "       tooldns install-mcp     # install from marketplace (GitHub, Gmail, Slack...)"
echo ""
echo -e "  2. ${BOLD}Create agent API keys:${NC}  (separate key per agent/customer)"
echo -e "       tooldns key-create"
echo ""
echo -e "${BOLD}USEFUL COMMANDS${NC}"
echo -e "  tooldns                    # interactive menu"
echo -e "  tooldns status             # service health check"
echo -e "  tooldns stats              # token savings report"
echo -e "  tooldns doctor             # diagnose common issues"
echo -e "  tooldns export             # backup config + data"
echo -e "  tooldns key-list           # list keys + usage"
echo -e "  tooldns key-create         # create a new key"
echo -e "  tooldns update             # pull latest + restart"
echo -e "  journalctl -u tooldns -f   # raw systemd logs"
echo -e "  journalctl -u tooldns-mcp -f"
echo ""
echo -e "  All management is done via the CLI: run ${BOLD}tooldns${NC} for the interactive menu."
echo ""
echo -e "${DIM}  Docs: https://github.com/syedfahimdev/ToolsDNS${NC}"
echo ""
