#!/usr/bin/env bash
# deploy.sh — One-command ToolsDNS backend installer for Ubuntu/Debian VPS
# Usage: curl -sSL https://raw.githubusercontent.com/syedfahimdev/ToolsDNS/master/deploy.sh | bash
# Or:    ./deploy.sh

set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*"; exit 1; }
section() { echo -e "\n${BOLD}──── $* ────${NC}"; }

# ── Config ────────────────────────────────────────────────────────────────────
INSTALL_DIR="${TOOLDNS_INSTALL_DIR:-/opt/tooldns}"
DATA_DIR="${TOOLDNS_DATA_DIR:-/root/.tooldns}"
PORT="${TOOLDNS_PORT:-8787}"
SERVICE_USER="root"

section "ToolsDNS Backend Installer"
echo "Install dir : $INSTALL_DIR"
echo "Data dir    : $DATA_DIR"
echo "Port        : $PORT"
echo ""

# ── Check root ─────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  error "Run as root: sudo bash deploy.sh"
fi

# ── Dependencies ─────────────────────────────────────────────────────────────
section "Installing system dependencies"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq python3 python3-pip python3-venv git curl 2>/dev/null
info "System packages OK"

# ── Clone / update repo ───────────────────────────────────────────────────────
section "Setting up ToolsDNS code"
if [[ -d "$INSTALL_DIR/.git" ]]; then
  info "Repo exists — pulling latest"
  git -C "$INSTALL_DIR" pull --ff-only
else
  info "Cloning repo to $INSTALL_DIR"
  git clone https://github.com/syedfahimdev/ToolsDNS.git "$INSTALL_DIR"
fi

# ── Python env ────────────────────────────────────────────────────────────────
section "Setting up Python environment"
python3 -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/pip" install -q --upgrade pip
"$INSTALL_DIR/.venv/bin/pip" install -q -e "$INSTALL_DIR"
info "Python venv ready"

# ── Data directory ────────────────────────────────────────────────────────────
section "Configuring data directory"
mkdir -p "$DATA_DIR/skills" "$DATA_DIR/tools"

ENV_FILE="$DATA_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  # Generate a random admin API key
  API_KEY="td_$(openssl rand -hex 24)"
  cat > "$ENV_FILE" << EOF
# ToolsDNS configuration
# Generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

TOOLDNS_API_KEY=$API_KEY
TOOLDNS_HOST=0.0.0.0
TOOLDNS_PORT=$PORT
TOOLDNS_APP_NAME=ToolsDNS
TOOLDNS_APP_TAGLINE=DNS for AI Tools

# Optional: set your model for token savings tracking
# TOOLDNS_MODEL=claude-sonnet-4-6

# Optional: Composio for 2000+ tools
# COMPOSIO_API_KEY=your_key_here
# COMPOSIO_MCP_URL=your_mcp_url_here
EOF
  info "Created $ENV_FILE with new API key: $API_KEY"
  warn "Save this API key! You'll need it for the frontend."
else
  info "Existing $ENV_FILE kept (not overwritten)"
  API_KEY=$(grep TOOLDNS_API_KEY "$ENV_FILE" | cut -d= -f2 | tr -d ' ')
fi

# ── Systemd service ───────────────────────────────────────────────────────────
section "Installing systemd service"
cat > /etc/systemd/system/tooldns.service << EOF
[Unit]
Description=ToolsDNS — AI Tool Discovery Service
Documentation=https://github.com/syedfahimdev/ToolsDNS
After=network.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$DATA_DIR/.env
ExecStart=$INSTALL_DIR/.venv/bin/python3 -m tooldns.cli serve
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=tooldns
ReadWritePaths=$DATA_DIR $INSTALL_DIR
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable tooldns
systemctl restart tooldns
sleep 4

if systemctl is-active --quiet tooldns; then
  info "ToolsDNS service running"
else
  error "Service failed to start. Check: journalctl -u tooldns -n 30"
fi

# ── Health check ──────────────────────────────────────────────────────────────
section "Verifying backend"
for i in {1..12}; do
  HEALTH=$(curl -s --max-time 3 "http://localhost:$PORT/health" 2>/dev/null || true)
  if echo "$HEALTH" | grep -q "healthy"; then
    info "Backend healthy: $HEALTH"
    break
  fi
  sleep 5
done

# ── Summary ───────────────────────────────────────────────────────────────────
section "Done!"
echo ""
echo -e "  ${BOLD}Backend URL${NC}  : http://localhost:$PORT"
echo -e "  ${BOLD}Admin API Key${NC}: $API_KEY"
echo -e "  ${BOLD}Web UI${NC}       : http://localhost:$PORT/ui"
echo -e "  ${BOLD}Logs${NC}         : journalctl -u tooldns -f"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo "  1. Point api.toolsdns.com → this server's IP"
echo "  2. Add TOOLDNS_API_URL=https://api.toolsdns.com to Vercel"
echo "  3. Add TOOLDNS_API_KEY=$API_KEY to Vercel"
echo ""
warn "If using Caddy/nginx, proxy port $PORT behind HTTPS."
